### PR TITLE
AS#118090147171048, Mail chimp Integration

### PR DESCRIPTION
**Pull request by vikasrohit**
-- Added constants

@parthshah @nlitwin @aselbie I have to add many constants for mailchimp. While MAILCHIMP_LIST_ID is required(please let me know if otherwise) in any case, I can get rid of constants for ids of newsletters by making one extra mailchimp api call. However, for getting first version out and saving one extra http call on skill-picker page load, I have added them. Now, my concern is the security. Should we really commit these ids in github? Even if get it using calling mailchimp api, we would have these ids in plain text in the calling page (skill picker for topcoder-app). Please note, right now I have copied, for all 3 env, the ids of a temporary list which I have created for testing. So, in case, we decide not to include these ids in github, I can safely remove these newsletters from the temporary list and recreated new one for testing.

### CODE REVIEW

**Comment by aselbie** [comment]
I don't think that the client ID is considered sensitive and could not find anything in Mailchimp's docs to indicate they would be. They are, by their nature, exposed in plain text to the client. Anyone bent on acquiring those IDs doesn't have to dig particularly deep.

The only worry I can see about committing them to Github is that it makes it easier to scrape. I don't think, though, that Mailchimp IDs would be of particularly high priority, and the damage they could do without the API key would be minimal.

**Comment by vikasrohit** [comment]
Thanks @aselbie I think the same. However, the ids, I have committed are not technically client ids. Anyway, I would try to minimize the number of ids to be exposed today.

**Comment by vikasrohit** [comment]
Merging for now. Will try to enhance it with next set of fixes.

**Comment by nlitwin** [comment]
Will the IDs be the same for dev / qa / prod in the end?

**Comment by vikasrohit** [comment]
Nopes, they would be different for all env. However, I think we have single mailchimp account for all environments. It would be best if we can have different mailchimp accounts, however, we can manage env isolation with different API keys and different mailing lists.

**Pull request merged**
